/*
 * This file is generated by jOOQ.
 */
package org.example.table_generated.public_.tables.records;


import org.example.table_generated.public_.tables.Stat;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatRecord extends UpdatableRecordImpl<StatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.stat.email_count</code>.
     */
    public void setEmailCount(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.stat.email_count</code>.
     */
    public Integer getEmailCount() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.stat.id</code>.
     */
    public void setId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.stat.id</code>.
     */
    public Integer getId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.stat.no_domains</code>.
     */
    public void setNoDomains(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.stat.no_domains</code>.
     */
    public Integer getNoDomains() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.stat.users_count</code>.
     */
    public void setUsersCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.stat.users_count</code>.
     */
    public Integer getUsersCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.stat.domain_with_most_emails</code>.
     */
    public void setDomainWithMostEmails(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.stat.domain_with_most_emails</code>.
     */
    public String getDomainWithMostEmails() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatRecord
     */
    public StatRecord() {
        super(Stat.STAT);
    }

    /**
     * Create a detached, initialised StatRecord
     */
    public StatRecord(Integer emailCount, Integer id, Integer noDomains, Integer usersCount, String domainWithMostEmails) {
        super(Stat.STAT);

        setEmailCount(emailCount);
        setId(id);
        setNoDomains(noDomains);
        setUsersCount(usersCount);
        setDomainWithMostEmails(domainWithMostEmails);
        resetChangedOnNotNull();
    }
}
