/*
 * This file is generated by jOOQ.
 */
package org.example.table_generated.public_;


import org.example.table_generated.public_.tables.AllesUser;
import org.example.table_generated.public_.tables.Email;
import org.example.table_generated.public_.tables.Rate;
import org.example.table_generated.public_.tables.Stat;
import org.example.table_generated.public_.tables.records.AllesUserRecord;
import org.example.table_generated.public_.tables.records.EmailRecord;
import org.example.table_generated.public_.tables.records.RateRecord;
import org.example.table_generated.public_.tables.records.StatRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AllesUserRecord> ALLES_USER_PKEY = Internal.createUniqueKey(AllesUser.ALLES_USER, DSL.name("alles_user_pkey"), new TableField[] { AllesUser.ALLES_USER.ID }, true);
    public static final UniqueKey<AllesUserRecord> UNIQUE_USERNAME = Internal.createUniqueKey(AllesUser.ALLES_USER, DSL.name("unique_username"), new TableField[] { AllesUser.ALLES_USER.USERNAME }, true);
    public static final UniqueKey<EmailRecord> EMAIL_PKEY = Internal.createUniqueKey(Email.EMAIL, DSL.name("email_pkey"), new TableField[] { Email.EMAIL.ID }, true);
    public static final UniqueKey<RateRecord> RATE_PKEY = Internal.createUniqueKey(Rate.RATE, DSL.name("rate_pkey"), new TableField[] { Rate.RATE.ID }, true);
    public static final UniqueKey<StatRecord> STAT_PKEY = Internal.createUniqueKey(Stat.STAT, DSL.name("stat_pkey"), new TableField[] { Stat.STAT.ID }, true);
}
