/*
 * This file is generated by jOOQ.
 */
package org.example.table_generated.public_;


import java.util.Arrays;
import java.util.List;

import org.example.table_generated.DefaultCatalog;
import org.example.table_generated.public_.tables.AllesUser;
import org.example.table_generated.public_.tables.Email;
import org.example.table_generated.public_.tables.Rate;
import org.example.table_generated.public_.tables.Stat;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.alles_user</code>.
     */
    public final AllesUser ALLES_USER = AllesUser.ALLES_USER;

    /**
     * The table <code>public.email</code>.
     */
    public final Email EMAIL = Email.EMAIL;

    /**
     * The table <code>public.rate</code>.
     */
    public final Rate RATE = Rate.RATE;

    /**
     * The table <code>public.stat</code>.
     */
    public final Stat STAT = Stat.STAT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AllesUser.ALLES_USER,
            Email.EMAIL,
            Rate.RATE,
            Stat.STAT
        );
    }
}
