/*
 * This file is generated by jOOQ.
 */
package org.example.table_generated.public_;


import org.example.table_generated.public_.tables.AllesUser;
import org.example.table_generated.public_.tables.Email;
import org.example.table_generated.public_.tables.Rate;
import org.example.table_generated.public_.tables.Stat;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.alles_user</code>.
     */
    public static final AllesUser ALLES_USER = AllesUser.ALLES_USER;

    /**
     * The table <code>public.email</code>.
     */
    public static final Email EMAIL = Email.EMAIL;

    /**
     * The table <code>public.rate</code>.
     */
    public static final Rate RATE = Rate.RATE;

    /**
     * The table <code>public.stat</code>.
     */
    public static final Stat STAT = Stat.STAT;
}
