/*
 * This file is generated by jOOQ.
 */
package org.example.table_generated.pg_catalog.tables.records;


import org.example.table_generated.pg_catalog.tables.GenerateSeries;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GenerateSeriesRecord extends TableRecordImpl<GenerateSeriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pg_catalog.generate_series.generate_series</code>.
     */
    public void setGenerateSeries(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.generate_series.generate_series</code>.
     */
    public Long getGenerateSeries() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GenerateSeriesRecord
     */
    public GenerateSeriesRecord() {
        super(GenerateSeries.GENERATE_SERIES);
    }

    /**
     * Create a detached, initialised GenerateSeriesRecord
     */
    public GenerateSeriesRecord(Long generateSeries) {
        super(GenerateSeries.GENERATE_SERIES);

        setGenerateSeries(generateSeries);
        resetChangedOnNotNull();
    }
}
