/*
 * This file is generated by jOOQ.
 */
package org.example.table_generated.public_.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.example.table_generated.public_.Keys;
import org.example.table_generated.public_.Public;
import org.example.table_generated.public_.tables.records.AllesUserRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllesUser extends TableImpl<AllesUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.alles_user</code>
     */
    public static final AllesUser ALLES_USER = new AllesUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AllesUserRecord> getRecordType() {
        return AllesUserRecord.class;
    }

    /**
     * The column <code>public.alles_user.id</code>.
     */
    public final TableField<AllesUserRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.alles_user.password</code>.
     */
    public final TableField<AllesUserRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.alles_user.role</code>.
     */
    public final TableField<AllesUserRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.alles_user.username</code>.
     */
    public final TableField<AllesUserRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(255), this, "");

    private AllesUser(Name alias, Table<AllesUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AllesUser(Name alias, Table<AllesUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.alles_user</code> table reference
     */
    public AllesUser(String alias) {
        this(DSL.name(alias), ALLES_USER);
    }

    /**
     * Create an aliased <code>public.alles_user</code> table reference
     */
    public AllesUser(Name alias) {
        this(alias, ALLES_USER);
    }

    /**
     * Create a <code>public.alles_user</code> table reference
     */
    public AllesUser() {
        this(DSL.name("alles_user"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AllesUserRecord, Integer> getIdentity() {
        return (Identity<AllesUserRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AllesUserRecord> getPrimaryKey() {
        return Keys.ALLES_USER_PKEY;
    }

    @Override
    public List<UniqueKey<AllesUserRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_USERNAME);
    }

    @Override
    public AllesUser as(String alias) {
        return new AllesUser(DSL.name(alias), this);
    }

    @Override
    public AllesUser as(Name alias) {
        return new AllesUser(alias, this);
    }

    @Override
    public AllesUser as(Table<?> alias) {
        return new AllesUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AllesUser rename(String name) {
        return new AllesUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AllesUser rename(Name name) {
        return new AllesUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AllesUser rename(Table<?> name) {
        return new AllesUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllesUser where(Condition condition) {
        return new AllesUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllesUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllesUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllesUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AllesUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AllesUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AllesUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AllesUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllesUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AllesUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
