/*
 * This file is generated by jOOQ.
 */
package org.example.table_generated.public_.tables;


import java.util.Collection;

import org.example.table_generated.public_.Keys;
import org.example.table_generated.public_.Public;
import org.example.table_generated.public_.tables.records.EmailRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Email extends TableImpl<EmailRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.email</code>
     */
    public static final Email EMAIL = new Email();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailRecord> getRecordType() {
        return EmailRecord.class;
    }

    /**
     * The column <code>public.email.id</code>.
     */
    public final TableField<EmailRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.email.date</code>.
     */
    public final TableField<EmailRecord, String> DATE = createField(DSL.name("date"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.email.domain</code>.
     */
    public final TableField<EmailRecord, String> DOMAIN = createField(DSL.name("domain"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.email.emails</code>.
     */
    public final TableField<EmailRecord, String[]> EMAILS = createField(DSL.name("emails"), SQLDataType.VARCHAR(255).array(), this, "");

    private Email(Name alias, Table<EmailRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Email(Name alias, Table<EmailRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.email</code> table reference
     */
    public Email(String alias) {
        this(DSL.name(alias), EMAIL);
    }

    /**
     * Create an aliased <code>public.email</code> table reference
     */
    public Email(Name alias) {
        this(alias, EMAIL);
    }

    /**
     * Create a <code>public.email</code> table reference
     */
    public Email() {
        this(DSL.name("email"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<EmailRecord, Integer> getIdentity() {
        return (Identity<EmailRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<EmailRecord> getPrimaryKey() {
        return Keys.EMAIL_PKEY;
    }

    @Override
    public Email as(String alias) {
        return new Email(DSL.name(alias), this);
    }

    @Override
    public Email as(Name alias) {
        return new Email(alias, this);
    }

    @Override
    public Email as(Table<?> alias) {
        return new Email(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Email rename(String name) {
        return new Email(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Email rename(Name name) {
        return new Email(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Email rename(Table<?> name) {
        return new Email(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email where(Condition condition) {
        return new Email(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Email where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Email where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Email where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Email where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Email whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
