/*
 * This file is generated by jOOQ.
 */
package org.example.table_generated.public_.tables;


import java.util.Collection;

import org.example.table_generated.public_.Keys;
import org.example.table_generated.public_.Public;
import org.example.table_generated.public_.tables.records.StatRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stat extends TableImpl<StatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.stat</code>
     */
    public static final Stat STAT = new Stat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StatRecord> getRecordType() {
        return StatRecord.class;
    }

    /**
     * The column <code>public.stat.email_count</code>.
     */
    public final TableField<StatRecord, Integer> EMAIL_COUNT = createField(DSL.name("email_count"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.stat.id</code>.
     */
    public final TableField<StatRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.stat.no_domains</code>.
     */
    public final TableField<StatRecord, Integer> NO_DOMAINS = createField(DSL.name("no_domains"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.stat.users_count</code>.
     */
    public final TableField<StatRecord, Integer> USERS_COUNT = createField(DSL.name("users_count"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.stat.domain_with_most_emails</code>.
     */
    public final TableField<StatRecord, String> DOMAIN_WITH_MOST_EMAILS = createField(DSL.name("domain_with_most_emails"), SQLDataType.VARCHAR(255), this, "");

    private Stat(Name alias, Table<StatRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Stat(Name alias, Table<StatRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.stat</code> table reference
     */
    public Stat(String alias) {
        this(DSL.name(alias), STAT);
    }

    /**
     * Create an aliased <code>public.stat</code> table reference
     */
    public Stat(Name alias) {
        this(alias, STAT);
    }

    /**
     * Create a <code>public.stat</code> table reference
     */
    public Stat() {
        this(DSL.name("stat"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<StatRecord, Integer> getIdentity() {
        return (Identity<StatRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<StatRecord> getPrimaryKey() {
        return Keys.STAT_PKEY;
    }

    @Override
    public Stat as(String alias) {
        return new Stat(DSL.name(alias), this);
    }

    @Override
    public Stat as(Name alias) {
        return new Stat(alias, this);
    }

    @Override
    public Stat as(Table<?> alias) {
        return new Stat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Stat rename(String name) {
        return new Stat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stat rename(Name name) {
        return new Stat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stat rename(Table<?> name) {
        return new Stat(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stat where(Condition condition) {
        return new Stat(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stat where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stat where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stat where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stat where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stat where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stat where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stat where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stat whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stat whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
