/*
 * This file is generated by jOOQ.
 */
package org.example.table_generated.information_schema.tables.records;


import org.example.table_generated.information_schema.tables.InformationSchemaCatalogName;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationSchemaCatalogNameRecord extends TableRecordImpl<InformationSchemaCatalogNameRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>information_schema.information_schema_catalog_name.catalog_name</code>.
     */
    public void setCatalogName(String value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>information_schema.information_schema_catalog_name.catalog_name</code>.
     */
    public String getCatalogName() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InformationSchemaCatalogNameRecord
     */
    public InformationSchemaCatalogNameRecord() {
        super(InformationSchemaCatalogName.INFORMATION_SCHEMA_CATALOG_NAME);
    }

    /**
     * Create a detached, initialised InformationSchemaCatalogNameRecord
     */
    public InformationSchemaCatalogNameRecord(String catalogName) {
        super(InformationSchemaCatalogName.INFORMATION_SCHEMA_CATALOG_NAME);

        setCatalogName(catalogName);
        resetChangedOnNotNull();
    }
}
