import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class WorkPanel extends JPanel {
    private JButton startBtn;
    private JLabel timerLabel;
    private JButton stopBtn;
    private JPanel showWork;
    private Timer timer;
    private long endTime = -1;
    private long duration = 1200000;
    private long elapsed = duration;
    private AudioControl audioControl;

    WorkPanel() {
        audioControl = new AudioControl();
        add(showWork);
        timer = createNewTimer();

        timer.setInitialDelay(0);

        startBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (elapsed <= 0) {
                    duration = 1200000;
                    elapsed = duration;
                    timer = createNewTimer();
                }
                timer.start();
            }
        });

        stopBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                duration = elapsed;
                endTime = -1;
                timer.stop();
                audioControl.stop();
            }
        });
    }

    private Timer createNewTimer() {
        return new Timer(10, (ActionListener) e -> {
            if (endTime < 0) {
                endTime = System.currentTimeMillis() + duration;
            }
            long now = System.currentTimeMillis();
            elapsed = endTime - now;
            if (elapsed <= 0) {
                audioControl.play();
                timer.stop();
            }
            long seconds = elapsed / 1000;
            long minutes = seconds / 60;
            this.timerLabel.setText(String.format("%d:%d", minutes, seconds % 60));
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        showWork = new JPanel();
        showWork.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        timerLabel = new JLabel();
        timerLabel.setText("...");
        showWork.add(timerLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        startBtn = new JButton();
        startBtn.setText("Start");
        showWork.add(startBtn, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        stopBtn = new JButton();
        stopBtn.setText("Pause");
        showWork.add(stopBtn, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return showWork;
    }
}
